import type { FinancialKpiId } from "./financial-types";

export type AppleMetricId =
  | "revenue"
  | "gross-profit"
  | "operating-income"
  | "net-income"
  | "diluted-eps"
  | "operating-cash-flow"
  | "capital-expenditure"
  | "free-cash-flow"
  | "cash-and-equivalents"
  | "total-debt";

export type AppleMetricGroup =
  | "performance"
  | "cash-generation"
  | "financial-position";

export type EvidenceRelationship = "supports" | "weakens" | "neutral";

export interface AppleMetricOption {
  id: AppleMetricId;
  label: string;
  shortDescription: string;
  group: AppleMetricGroup;
  derived?: boolean;
  nonGaap?: boolean;
}

export const APPLE_METRIC_GROUPS: Array<{
  id: AppleMetricGroup;
  label: string;
}> = [
  { id: "performance", label: "Performance" },
  { id: "cash-generation", label: "Cash generation" },
  { id: "financial-position", label: "Financial position" },
];

export const APPLE_METRIC_OPTIONS: AppleMetricOption[] = [
  {
    id: "revenue",
    label: "Revenue",
    shortDescription: "Total net sales for the fiscal year.",
    group: "performance",
  },
  {
    id: "gross-profit",
    label: "Gross Profit",
    shortDescription: "Sales left after direct product and service costs.",
    group: "performance",
  },
  {
    id: "operating-income",
    label: "Operating Income",
    shortDescription: "Profit from core operations before interest and taxes.",
    group: "performance",
  },
  {
    id: "net-income",
    label: "Net Income",
    shortDescription: "Bottom-line profit after all expenses and taxes.",
    group: "performance",
  },
  {
    id: "diluted-eps",
    label: "Diluted EPS",
    shortDescription: "Earnings per share including potential dilution.",
    group: "performance",
  },
  {
    id: "operating-cash-flow",
    label: "Operating Cash Flow",
    shortDescription: "Cash generated by core operations during the year.",
    group: "cash-generation",
  },
  {
    id: "capital-expenditure",
    label: "Capital Expenditure",
    shortDescription: "Cash spent on property, plant, and equipment (positive spend).",
    group: "cash-generation",
  },
  {
    id: "free-cash-flow",
    label: "Free Cash Flow",
    shortDescription: "Derived non-GAAP: Operating Cash Flow − CapEx.",
    group: "cash-generation",
    derived: true,
    nonGaap: true,
  },
  {
    id: "cash-and-equivalents",
    label: "Cash & Equivalents",
    shortDescription: "Cash and cash equivalents at fiscal year-end.",
    group: "financial-position",
  },
  {
    id: "total-debt",
    label: "Total Debt",
    shortDescription: "Commercial paper plus current and noncurrent term debt.",
    group: "financial-position",
    derived: true,
  },
];

/** Harborline Sprint 0 still only enables revenue. */
export const harborlineKpiOptions: Array<{
  id: FinancialKpiId;
  label: string;
  status: "enabled" | "coming-soon";
}> = [{ id: "revenue", label: "Revenue", status: "enabled" }];

export function formatAppleMetricValue(
  value: number,
  displayFormat: string,
  currency: string,
): { exact: string; compact: string } {
  if (displayFormat === "per-share") {
    const exact = new Intl.NumberFormat("en-US", {
      style: "currency",
      currency,
      minimumFractionDigits: 2,
      maximumFractionDigits: 4,
    }).format(value);
    return { exact: `${exact}/share`, compact: exact };
  }

  if (displayFormat === "percent") {
    const exact = `${value.toFixed(1)}%`;
    return { exact, compact: exact };
  }

  const exact = new Intl.NumberFormat("en-US", {
    style: "currency",
    currency,
    maximumFractionDigits: 0,
  }).format(value);

  const abs = Math.abs(value);
  const sign = value < 0 ? "-" : "";
  let compact: string;
  if (abs >= 1_000_000_000_000) {
    compact = `${sign}$${(abs / 1_000_000_000_000).toFixed(2)}t`;
  } else if (abs >= 1_000_000_000) {
    compact = `${sign}$${(abs / 1_000_000_000).toFixed(2)}b`;
  } else if (abs >= 1_000_000) {
    compact = `${sign}$${(abs / 1_000_000).toFixed(1)}m`;
  } else {
    compact = exact;
  }

  return { exact, compact };
}

export function formatMarginPercent(value: number | null | undefined): string {
  if (value === null || value === undefined || Number.isNaN(value)) return "—";
  return `${value.toFixed(1)}%`;
}

export function formatPercentagePoints(
  value: number | null | undefined,
): string {
  if (value === null || value === undefined || Number.isNaN(value)) return "—";
  const sign = value > 0 ? "+" : "";
  return `${sign}${value.toFixed(1)} pp`;
}

export function formatNetDebtValue(
  value: number | null | undefined,
  isNetCash: boolean,
  currency: string,
): string {
  if (value === null || value === undefined || Number.isNaN(value)) return "—";
  const magnitude = formatAppleMetricValue(Math.abs(value), "currency", currency).compact;
  return isNetCash ? `Net cash ${magnitude}` : `Net debt ${magnitude}`;
}
