<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>TenYearExplorer.Api</RootNamespace>
    <UserSecretsId>6aecbb0b-831a-452a-88df-419c53793ec1</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TenYearExplorer.Application\TenYearExplorer.Application.csproj" />
    <ProjectReference Include="..\TenYearExplorer.Infrastructure\TenYearExplorer.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\fixtures\**\*" LinkBase="fixtures" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
